<a href="https://colab.research.google.com/github/mahyamadelta/Pytorch_Learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.12257416, 0.12496421, 0.38794775, 0.68235304],
       [0.54747868, 0.52096433, 0.5592457 , 0.15389117],
       [0.14154449, 0.30761348, 0.07523257, 0.40976336]])

In [5]:
np1.dtype

dtype('float64')

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1226, 0.1250, 0.3879, 0.6824],
        [0.5475, 0.5210, 0.5592, 0.1539],
        [0.1415, 0.3076, 0.0752, 0.4098]], dtype=torch.float64)